FROM mcr.microsoft.com/playwright/python:v1.58.0-noble

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Python deps
COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir -r requirements-dev.txt

RUN apt-get update && apt-get install -y nodejs npm

# Node deps
COPY package.json package-lock.json .
RUN npm ci

# Código
COPY . .

# Run tests
CMD ["npx", "playwright", "test", "--project=chromium"]
